name: CI checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  ci_checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: [lint, style-check, type-check]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Upgrade PIP
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -e .[dev]
      - name: Run ${{ matrix.command }}
        run: make ${{ matrix.command }}
